server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_performance
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.student.performance: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
